### ISSUE TITLE
issue with zlib

### ISSUE THREAD

**Issue by labba** [niXman/mingw-builds#512]
i'm on windows 10 x64

trying to build the following:
./build --mode=gcc-8.4.0 --arch=x86_64

getting error on zlib that it's have wrong arguments when trying to run the test/example.c

**Comment by niXman** [comment]
try to uncomment `set MSYS=winsymlinks:nativestrict` line in the `msys2_shell.cmd` file and restart it as admin.

**Comment by labba** [comment]
thanks!

done that and it moved on but later on failed during the gcc  compilation

-> gcc-8.4.0
--> download gcc-8.4.0.tar.xz... done
--> unpack gcc-8.4.0.tar.xz... done
--> patching... done
--> configure... done
--> building...

error!


in the log file the error i got are here in the attached files
[configure.log](https://github.com/niXman/mingw-builds/files/4824911/configure.log)

[make.log](https://github.com/niXman/mingw-builds/files/4824910/make.log)

**Comment by kov-serg** [comment]
niXman: May be you should hardcode __USE_MINGW_ANSI_STDIO into build script?
I think he has same issue with %llu and %llx
labba: try to erase intermediate files and compile with ./build --mode=gcc-8.4.0 --arch=x86_64 --rt-version=v7

**Comment by niXman** [comment]
@labba please remove `/home/labba/mingw-gcc-8.4.0` dir and restart again as: `./build --mode=gcc-8.4.0 --arch=x86_x64 --rt-version=v7`

@kov-serg I think you are right, will do.

**Comment by niXman** [comment]
> May be you should hardcode __USE_MINGW_ANSI_STDIO into build script?

no, I think be better to set `v7` as default version of used runtime...

**Comment by niXman** [comment]
done: https://github.com/niXman/mingw-builds/commit/d4f95f264ce2f2a2fb05ca0ceef2a888b4c8222e

**Comment by labba** [comment]
i have deleted everything and used the new command line with the new option of --rt-version=v7 but still after trying to build gcc getting errors

please see here logs

[make.log](https://github.com/niXman/mingw-builds/files/4827968/make.log)
[configure.log](https://github.com/niXman/mingw-builds/files/4827970/configure.log)

**Comment by kov-serg** [comment]
```
configure: error: in `/home/labba/mingw-gcc-8.4.0/x86_64-840-posix-sjlj-rt_v7/build/gcc-8.4.0/x86_64-w64-mingw32/32/libgomp':
configure: error: C compiler cannot create executables
See `config.log' for more details.
```
where is config.log

**Comment by kov-serg** [comment]
remove all and reinstall msys2 and build script try again. I build it tonight with out problem.
```
./build --mode=gcc-8.4.0 --arch=x86_64 --rt-version=v7
...
--> execute i686: "dll_test2.exe" ...             -> 0 -> done
--> gcc      x86_64: "pthread_test.c" ...         -> 0 -> done
--> execute x86_64: "pthread_test.exe" ...        -> 0 -> done
--> gcc      i686: "pthread_test.c" ...           -> 0 -> done
--> execute i686: "pthread_test.exe" ...          -> 0 -> done

User@T1 MSYS ~/mingw-builds-develop
# cd ~/mingw-gcc-8.4.0/x86_64-840-posix-sjlj-rt_v7/mingw64
User@T1 MSYS ~/mingw-gcc-8.4.0/x86_64-840-posix-sjlj-rt_v7/mingw64
# du -sh
533M    .
```

**Comment by labba** [comment]
for the 8.4.0 done the following:

> ./build --mode=gcc-8.4.0 --arch=x86_64 --rt-version=v7 --threads=win32 --enable-languages=c,c++

i get this issue:

> checking for x86_64-w64-mingw32-gcc... /home/gcc/mingw-gcc-8.4.0/x86_64-840-win32-sjlj-rt_v7/build/gcc-8.4.0/./gcc/xgcc -B/home/gcc/mingw-gcc-8.4.0/x86_64-840-win32-sjlj-rt_v7/build/gcc-8.4.0/./gcc/ -L/mingw64/x86_64-w64-mingw32/lib -L/mingw64/mingw/lib -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/mingw/include -B/mingw64/x86_64-w64-mingw32/bin/ -B/mingw64/x86_64-w64-mingw32/lib/ -isystem /mingw64/x86_64-w64-mingw32/include -isystem /mingw64/x86_64-w64-mingw32/sys-include  -m32
> checking for C compiler default output file name... 
> configure: error: in `/home/gcc/mingw-gcc-8.4.0/x86_64-840-win32-sjlj-rt_v7/build/gcc-8.4.0/x86_64-w64-mingw32/32/libgomp':
> configure: error: C compiler cannot create executables
> See `config.log' for more details.
> make[1]: *** [Makefile:14093: configure-target-libgomp] Error 1
> make[1]: Leaving directory '/home/gcc/mingw-gcc-8.4.0/x86_64-840-win32-sjlj-rt_v7/build/gcc-8.4.0'




tried building the following:

> ./build --mode=gcc-8.3.0 --arch=x86_64 --rt-version=v7 --threads=win32 --enable-languages=c,c++

still fail for me,

> configure: error: in `/home/gcc/mingw-gcc-8.3.0/x86_64-830-win32-sjlj-rt_v7/build/gcc-8.3.0/x86_64-w64-mingw32/32/libgomp':
> configure: error: C compiler cannot create executables
> See `config.log' for more details.
> make[1]: *** [Makefile:14093: configure-target-libgomp] Error 1
> make[1]: Leaving directory '/home/gcc/mingw-gcc-8.3.0/x86_64-830-win32-sjlj-rt_v7/build/gcc-8.3.0'
> make: *** [Makefile:911: all] Error 2
> 

here is config log:
[config.log](https://github.com/niXman/mingw-builds/files/4842260/config.log)



can you please share your build system info ?
- OS ? bits ? 
- msys version


also i have read in the "readme" that there is a need to change - are the following changes that need to be done are still relevant ???
- In the MSYS2 file structure delete the /MinGW directory.
- Delete the paths pointing to any preinstalled MinGW from the PATH environment variable.

**Comment by kov-serg** [comment]
os: Windows 7x64 SP1
msys2: https://github.com/msys2/msys2-installer/releases/download/2020-06-02/msys2-x86_64-20200602.exe
script: https://codeload.github.com/niXman/mingw-builds/zip/develop

modify c:\msys64\msys2_shell.cmd
uncomment string with set MSYS=winsymlinks:nativestrict
unpacked script to c:\msys64\home\user\mingw-build-develop
msys2 shell should be run as admin or hardlinks will not work
cd ~/mingw-build-develop
pacman -S git subversion tar zip p7zip make patch automake autoconf libtool flex bison gettext gettext-devel wget sshpass texinfo autogen dejagnu lndir
./build --mode=gcc-8.4.0 --arch=x86_64 --rt-version=v7
it takes about 5Gb of space and about 3.5 hours to build from scratch using only one core from eight available.

ps: if internet is not stable in mingw-builds-develop/library/functions.sh line with
local _WGET_TRIES=10
value 10 should be changed to 0

pps: Your initial post was about 8.4.0, but config says you tring to building 8.3.0
ppps: You have to remove or rename /mingw64 directory

![gcc-01](https://user-images.githubusercontent.com/5946122/85959831-76adcc80-b9a7-11ea-95b6-cb504c9b2d5a.png)

**Comment by labba** [comment]
amazing now its working like it should!
i guess the issue was indeed related to the "mingw64" folder .. i have renamed it and it continue to compile well 

i have installed a VM with the same OS as you have and done the following:

```
OS: 
	Windows 7x64 SP1

install msys2: 
	https://github.com/msys2/msys2-installer/releases/download/2020-06-02/msys2-x86_64-20200602.exe

rename "C:\msys64\mingw64" directory == > "C:\msys64\MOD_mingw64_MOD"

modify "c:\msys64\msys2_shell.cmd":
	uncomment string with set MSYS=winsymlinks:nativestrict

"msys2_shell.cmd" - should be run as admin or hardlinks will not work

Install:
	pacman -S git subversion tar zip p7zip make patch automake autoconf libtool flex bison gettext gettext-devel wget sshpass texinfo autogen dejagnu lndir


git clone https://github.com/niXman/mingw-builds.git


cd mingw-build
./build --mode=gcc-8.3.0 --arch=x86_64 --rt-version=v7 --threads=win32 --enable-languages=c,c++

```
